# Disable the package module, hiding it from the prompt completely
add_newline = false

[aws]
disabled = true

# [aws.region_aliases]
# us-east-1 = "va"

# [docker_context]
# disabled = false
# only_with_files = false

[gcloud]
disabled = true

[character]
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[kubernetes]
disabled = true

# [line_break]
# disabled = true

[memory_usage]
disabled = true
show_percentage = true

[nodejs]
disabled = true

[package]
disabled = true

# GIT
[git_branch]
symbol = "ğŸŒ± "
truncation_symbol = ""

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[cmd_duration]
min_time = 500
format = " took [$duration](bold blue)"

[python]
style = "green bold"
